version: "3"

services:
  gard-flask-api:
    build: .
    ports:
      - "443:5000"
    environment:
        - SUPABASE_DB_URL=postgresql://postgres.lvtniondxozofixywyqq:$$M_X6CzEAB.P?3v@aws-0-eu-central-1.pooler.supabase.com:5432/postgres #$SUPABASE_DB_URL
        - PORT=443
